services:
  node01:
    build: .
    hostname: node01
    networks:
      hpl_net:
        ipv4_address: 172.20.0.2

  node02:
    build: .
    hostname: node02
    networks:
      hpl_net:
        ipv4_address: 172.20.0.3

  node03:
    build: .
    hostname: node03
    networks:
      hpl_net:
        ipv4_address: 172.20.0.4

  node04:
    build: .
    hostname: node04
    networks:
      hpl_net:
        ipv4_address: 172.20.0.5

networks:
  hpl_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 
